version: "3.7"
services:

  storagereport:
    image: ghcr.io/qumulo/storagereport:latest
    container_name: storagereport
    environment:
      - TZ=${TIMEZONE:-UTC}
    volumes:
      - type: bind
        source: $CONFIG_FILE
        target: /code/config/config.json
      - type: bind
        source: $REPORT_DIRECTORY
        target: /code/reports
        
